### ISSUE TITLE
"Revisa la información de registro"

### ISSUE THREAD

**Issue by josecurioso** [josecurioso/service.subtitles.tusubtitulo#1]
Problema reportado por @methodmann, al que no le funciona el addon en ninguna serie. [Conversación continuada aqui]

**Comment by josecurioso** [comment]
@methodmann el addon me funciona perfectamente en una instalación limpia de Kodi Krypton v17.3 Asegurate de que tienes instalada la ultima versión (1.2.0) y si el problema continúa desinstala, reinicia y vuelve a instalar desde el repositorio oficial (acaba de ser admitido). Siento no poder ser de más ayuda pero no soy capaz de reproducir el error. Si ninguna de esas cosas funciona pásame el log de kodi a ver si me dice algo.

**Comment by methodmann** [comment]
Tras eliminar el addon y reinstalar desde repositorio todo ok. Se me había actualizado al addon que liberó en su día elhappy. Gracias por el curro

**Comment by josecurioso** [comment]
De nada y a disfrutar de las series!.
