### ISSUE TITLE
Eliminar repositorio

### ISSUE THREAD

**Issue by TuSubtitulo** [josecurioso/service.subtitles.tusubtitulo#2]
Saludos. No hemos autorizado la publicación de ningún addon/Kodi para nuestra web.

Por esta razón, debe eliminar el repositorio publicado aquí. No ha pedido autorización para la creación del mismo, utilizar nuestro logo y nombre de la web.

GitHub da el privilegio de pedir la eliminación del mismo entre conversacón de ambas partes. De usted no querer, entablamos una solicitud para la eliminación por parte del staff de GitHub y su cuenta queda suspendida.

Esperamos acción responsable.

**Comment by TuSubtitulo** [comment]
Tiene que eliminarlo de kodi.tv y cualquier otra web de terceros. No hemos autorizado esta programación. De lo contrario, iremos por los canales administrativos.

**Comment by TuSubtitulo** [comment]
Segundo y último pedido que realizaremos antes de comunicarnos con el staff de GitHub quienes están al tanto ya de la situación. Debe eliminar el repositorio.

**Comment by susobaco** [comment]
Ostiá! ¡Difunde la palabra! o la cultura, ¿como era?

**Comment by TuSubtitulo** [comment]
Ya está removido de Kodi y ya nos hemos comunicado con GitHub para la eliminación del mismo viendo que no ha visto buena voluntad por su parte. Es necesario pedir autorización antes de trabajar.

**Comment by josecurioso** [comment]
@TuSubtitulo 

@susobaco ha dicho ya todo lo que merece ser dicho. Desde que subtitulos.es se perdió no habéis hecho más que caer, la semana pasada casi chapais la pagina por culpa de no menos que VUESTROS moderadores. Pero en cuanto alguien toma la iniciativa para ayudar a VUESTRA comunidad ni mas ni menos, sin recibir ni buscar nada a cambio la respuesta es esta. Te voy a explicar por que he pasado de pedir autorización, porque no soy el primero que hace esto ni el segundo.

**Comment by josecurioso** [comment]
@TuSubtitulo

Es más, voy más allá, este servicio no recarga un extra el servidor dado que usa los mismos métodos que un navegador, en cuanto a peticiones es igual que un humano a ojos de vuestro servidor con lo cual no hay excusa técnica para no permitir una cosa así.

Eso solo deja el tema de las donaciones cosa que dejo más que clara en este repositorio por encima de todo, pone y cito textual (traducido) en el README "Contrubuir: lo primero de todo puedes donar a tusubtitulo.com en su página y ayudar a mantener los servidores"

Por último la tercera excusa que he visto referida a este tema es que preferís "interactuar". Las únicas interacciones que veo de entre más de 4000 descargas que puede tener uno de vuestros subtitulos es gente quejandose de que no estan y gente quejandose de los primeros ademas de el ocasional mod diciendole al mundo lo mucho que le debe. Esos casos son en la caja de comentarios/interacción (no más de 25/4000)

**Comment by josecurioso** [comment]
@TuSubtitulo

Por último en cuanto a este repositorio en caso de que Github lo elimine procederé a hostearlo yo mismo si hace falta pero como aplicación opensource que es no se va a eliminar y eso si que no va a cambiar. Esta situación no se comenta en vuestros ToS (inexistentes) y ni los logotipos ni el nombre tienen copyright de ningún tipo a fecha de hoy.

**Comment by josecurioso** [comment]
@TuSubtitulo 

Con todo lo dicho anteriormente si en algún momento cambiáis de opinión y lo queréis hacer oficial para disfrute de vuestros usuarios aquí estoy para lo que queráis y sois más que libres de usar el código libre contenido en este repositorio. Un Saludo

**Comment by TuSubtitulo** [comment]
José, no tiene autorización para crear el plugin. Usted no lo remueve, nosotros lo bloqueamos desde el sistema y listo. Se ha dicho en sinfines de veces que estamos trabajando en algo. Por culpa de usuarios como usted, que hacen programaciones sin saber, sin saber las licencias que tenemos, nos atrasamos.

No diremos más, las licencias que tenemos son privadas y ya está reportado a GitHub. Usted lo sube a otro hosting, y espere un DMCA. No comentaremos más, las notificaciones legales serán lo próximo.

**Comment by josecurioso** [comment]
Si dices que no conozco las licencias que tenéis porque no me las explicas? Me gustaría saberlo porque en la página no he encontrado nada referente a este tema.

**Comment by TuSubtitulo** [comment]
Si hubiese pedido autorización, le hubiésemos permitido unirse al grupo de trabajo que existe en estos momentos, pero lamentablemente el salirse de los procesos no es lo correcto. Nuestro nombre y web están registradas y están bajo el United States Patent and Trademark Office. Lamentablemente tiene que seguir las reglas como todos.

**Comment by TuSubtitulo** [comment]
No discutiremos más este tema. Ya los reportes están hechos. Saludos.

**Comment by josecurioso** [comment]
Yo digo pocas cosas sin haber investigado antes y ya comprobé hace tiempo el registro mercantil español y el USPTO, bases de datos en las que no encontré ninguna referencia a vuestra marca. Te recomendaría anunciar el grupo de trabajo del que me hablas en la seccion de programadores del foro porque tampoco habia ninguna referencia a eso.

**Comment by TuSubtitulo** [comment]
Aclarar dos puntos. No somos subtitulos.es y no tenemos nada que ver con España. Sin nada más que decir, saludos.

**Comment by josecurioso** [comment]
Insisto, si creeis tener algun registro en el United States Patent and Trademark Office no salis en la base de datos así que revisadlo. Me repito ya que parece haberse ignorado, conviene avisar de ese grupo de trabajo en el foro.

**Comment by josecurioso** [comment]
[NOTA PARA EL FUTURO] En los últimos mensajes del hilo no hablo solo, el usuario "TuSubtitulo" eliminó los comentarios en cuanto se dio cuenta del ridículo que estaba haciendo al intentar pasar por administrador del sitio.

**Comment by okupa81** [comment]
José...genial aporte, muchísimas gracias por el trabajo. Funciona perfecto. Openelec/kypton
